name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Gradle Info
        run: ./gradlew -version

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      # To speed up lint check only run for release variant.
      - name: Run Lint
        run: ./gradlew :androidutils:lintRelease

      # Upload Lint report (also on error).
      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: Lint reports
          path: |
            androidutils/build/reports/lint-results-release.html